; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = .
include_dir = .
default_envs = 
	bluepill_f103c8
	blackpill_f411ce

[env]
lib_deps = 
	DCC-EX/DCCEXProtocol@^1.4.0
	; symlink:///home/pete/code/DCCEXProtocol
	olikraus/U8g2@^2.36.15
build_flags = 
	-std=c++17 -Os -g2
	-Wall
	-DSERIAL_RX_BUFFER_SIZE=256
	-DSERIAL_TX_BUFFER_SIZE=256
	-ffunction-sections
	-fdata-sections
build_src_filter =
	+<*>
	-<.git/>
	-<test/>
	-<src/>
test_ignore = *

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
upload_protocol = stlink
build_flags = 
	${env.build_flags}
	-DPIO_FRAMEWORK_ARDUINO_ENABLE_CDC
	-DUSBCON
	-DHAL_PCD_MODULE_ENABLED
	-DUSBD_VID=0x0483
	-DUSBD_PID=0x5740
	-DUSB_MANUFACTURER="Unknown"
	-DUSB_PRODUCT="\"BLUEPILL_F103C8\""
lib_deps = 
	${env.lib_deps}
build_src_filter =
  ${env.build_src_filter}
test_ignore =
  ${env.test_ignore}
monitor_speed = 115200
monitor_echo = yes

[env:blackpill_f411ce]
platform = ststm32
board = blackpill_f411ce
board_build.mcu = stm32f411ceu6
board_build.f_cpu = 100000000L
framework = arduino
upload_protocol = stlink
lib_deps = 
	${env.lib_deps}
build_flags = 
	${env.build_flags}
	-DPIO_FRAMEWORK_ARDUINO_ENABLE_CDC
	-DUSBCON
	-DHAL_PCD_MODULE_ENABLED
	-DUSBD_VID=0x0483
	-DUSBD_PID=0x5740
	-DUSB_MANUFACTURER="Unknown"
	-DUSB_PRODUCT="\"BLACKPILL_F411CE\""
build_src_filter =
  ${env.build_src_filter}
test_ignore =
  ${env.test_ignore}
monitor_speed = 115200
monitor_echo = yes

[env:native_test]
platform = native
lib_deps =
	googletest
test_framework = googletest
build_flags =
	${env.build_flags}
	-I./test/mocks
	-I./src
	-fsanitize=address	 # Address sanitizer
	-fsanitize=undefined # Undefined Behavior Sanitizer
	-g                   # Add debugging symbols
	-O0                  # Disable optimizations for better analysis
	-lgcov							 # Enable gcov reports
	--coverage					 # Enable test coverage tracking (gcno + gcna file generation)
	-fprofile-abs-path	 # Use absolute paths in coverage data
	-DNATIVE_TESTING
build_src_filter =
	+<*>
	+<src/>
	-<test/>
test_ignore = test_user_interaction
test_filter = *
test_build_src = yes

[env:native_test_windows]
; Windows cannot do sanitize checks
platform = native
lib_deps =
	googletest
test_framework = googletest
build_flags =
	${env.build_flags}
	-I./test/mocks
	-I./src
	-g                   # Add debugging symbols
	-O0                  # Disable optimizations for better analysis
	-lgcov							 # Enable gcov reports
	--coverage					 # Enable test coverage tracking (gcno + gcna file generation)
	-fprofile-abs-path	 # Use absolute paths in coverage data
	-DNATIVE_TESTING
build_src_filter =
	+<*>
	+<src/>
	-<test/>
test_ignore = test_user_interaction
test_filter = *
test_build_src = yes
